### ISSUE TITLE
Multiple build commands for NMSSH.h

### ISSUE THREAD

**Issue by afroimovitch** [NMSSH/NMSSH#159]
Seems like the file NMSSH.h is included twice once under NMSSH/ and once uder NMSSH-iOS.  This is causing a warning to be generated when building this pod.

**Comment by Jan-E** [comment]
I always remove the first NMSSH.h (which is for macOS) after a `pod install` in my iOS projects. Then Xcode asks something like 'remove reference only?'.

**Comment by Frugghi** [comment]
I've updated the podspec, let me know if the issue has not been fixed!

**Comment by Jan-E** [comment]
Just to confirm: `pod update NMSSH` solved this issue
