### ISSUE TITLE
Unable to find NMSSH.framework - IOS

### ISSUE THREAD

**Issue by kasperkruse** [NMSSH/NMSSH#169]
Hi. Thank you for a great project.

When I compile the IOS project file, I am unable to find the NMSSH.framework and add it to my project. What am I doing wrong?
I have been following the guide here: https://github.com/NMSSH/NMSSH/wiki/Build-and-use-in-your-iOS-project

Please see the attached file.

Best regards
Kasper
<img width="1354" alt="screen shot 2016-03-01 at 10 53 49" src="https://cloud.githubusercontent.com/assets/17566268/13423705/cb61c536-df9c-11e5-8cc6-ad497a5441c9.png">

**Comment by Lejdborg** [comment]
Have you set the correct build target? (The drop-down next to the deploy target)

**Comment by Frugghi** [comment]
The framework should be in the _Products_ folder in your filesystem, not the one you see from Xcode.

**Comment by kasperkruse** [comment]
Hi Christoffer.

You where right, I was missing that part. It works now.
Thank you very much :-)

Best regards
Kasper
