### ISSUE TITLE
I'm trying to autorize with authenticateByPublicKey but cannot

### ISSUE THREAD

**Issue by daicaga** [NMSSH/NMSSH#170]
Hi all,

If you guy have any solution for this, please help me!
This is urgent for me.

I'm using this library for connect SSH.
I tried to use as this code below but it's not successful:
```Objective-C
    self.ssh = [NMSSHSession connectToHost:@"<my server URL>" withUsername:@"<Mymail>"];
    if(self.ssh.isConnected) {
        [self.ssh authenticateByPublicKey:@"ssh-rsa MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKCzOVkd3toAOzZmfl4uMqCrNv\
         03+LtYOCi6bfDLWH/fG601SJXwDKcL+oFV3Hb4zH+W+NdPGQRL7C8AqKBT0TfBHu\
         C53SQiahYTCLomEhXXqH7P03aiYgjqDZMypwRGi2WEaOpfbijbR0kel2nygmTkaq\
         u0fbltGJBOgE2udKtwIDAQAB"
                               privateKey:@"MIICXAIBAAKBgQCKCzOVkd3toAOzZmfl4uMqCrNv03+LtYOCi6bfDLWH/fG601SJ\
         XwDKcL+oFV3Hb4zH+W+NdPGQRL7C8AqKBT0TfBHuC53SQiahYTCLomEhXXqH7P03\
         aiYgjqDZMypwRGi2WEaOpfbijbR0kel2nygmTkaqu0fbltGJBOgE2udKtwIDAQAB\
         AoGAVaVvgsv2iljuEt9ldO7ZDBuJiscI6lBa4KLujJLhChfXY5d8aqKD5hYgAxQG\
         lBc0nFm5CWXV/jF4vY+aqllns4WRDVve5ozMrhqgUDM37oRHsTTmKTNLNXvNn/rH\
         NZRhQpG6PyWvTHUGh0e/Ul0nagtez87A5b/eLaEzIorge3kCQQDQescuw8XbIWTp\
         PY/KAGVLGkAn72HijCLvipQC+ZSIiRcVa1BWpgcrqma8UXzgW8guQ5dl8CMqtTuj\
         DSiDvHjzAkEAqYJYGPuab1LIvZepdy4V2DM6zXnIs7O/tpOXu2ZNb2j82Cjy7CU4\
         Ac/aLjlw5+sqj//IF9U+/l27qO52LqPYLQJAbIn/eVFjiRpxtxzd54UdN2SLUj9G\
         7vOWnK/BL2tQ8WSuJ/Ce+v2lbg5hPloOcaBXL/7wq5nCNVH1ooYPOca+EQJACmUe\
         5/FOCDOocdACKXffCRIjMgSc5UBJqnWkoW5lo0Zp8wuX0hl6NMo9VAZbwS0vwALs\
         j2GZalnvLy3oe3W6xQJBAKwmm4MW9zLovw714kqDcJnWo6cLOV/z+97+GnY8EXnK\
         pG4l0Njy2TJk8xTCHMa3ScAEXECe8adRAjVEs5xO6k8="
                                  andPassword:nil];
    }
    
    if (self.ssh.isAuthorized) {
        NSError *err = nil;
        self.ssh.channel.delegate = self;
        //self.receiveView.text = [session.channel execute:@"ls" error:&err]; // works
        
        [self.ssh.channel startShell:&err];
        NSLog(@"Authentication succeeded");
    }
```

Regards,
Ga

**Comment by Frugghi** [comment]
Public key and private key are the file path to the public and private key, respectively.
You should use `- (BOOL)authenticateByInMemoryPublicKey:privateKey:andPassword:`

**Comment by buidinhnguyen** [comment]
We are also waiting for cocoapod for that new one.

**Comment by Frugghi** [comment]
You're right, I totally forgot about that. I've just pushed the new podspec to the Cocoapods repo!

**Comment by daicaga** [comment]
After pod 2.2.5, I tried to use: `- (BOOL)authenticateByInMemoryPublicKey:privateKey:andPassword:`
But I'm still got issue for auth as below, please help me!

`016-03-09 09:08:04.699 TestMySSH[30098:973689] NMSSH: libssh2 (v1.6.0) initialized
2016-03-09 09:08:04.699 TestMySSH[30098:973689] NMSSH: Start php-mytest7777.rhcloud.com resolution
2016-03-09 09:08:05.125 TestMySSH[30098:973689] NMSSH: Socket connection to 54.165.171.56 on port 22 succesful
2016-03-09 09:08:06.494 TestMySSH[30098:973689] NMSSH: Remote host banner is SSH-2.0-OpenSSH_5.3
2016-03-09 09:08:06.495 TestMySSH[30098:973689] NMSSH: The host's fingerprint is CF:EE:77:CB:0E:FC:02:D7:72:7E:AE:80:C0:90:88:A7
2016-03-09 09:08:06.495 TestMySSH[30098:973689] NMSSH: SSH session started
2016-03-09 09:08:06.764 TestMySSH[30098:973689] NMSSH: User auth list: publickey,gssapi-keyex,gssapi-with-mic
2016-03-09 09:08:07.008 TestMySSH[30098:973689] NMSSH: Public key authentication failed with reason -18`

I don't know why is my publickey is wrong. I use the tool to generate it and saved it to my config in server.

Regards,
Ga

**Comment by daicaga** [comment]
I saw that when we connect with server by user@host.
We need use: `authenticateByKeyboardInteractive` right? But I don't know how I can use it?

Again, thanks for you cool library!

Ga,

**Comment by Lejdborg** [comment]
In the logs you can see that publickey should work with your host `publickey,gssapi-keyex,gssapi-with-mic`. The error you are getting is `LIBSSH2_ERROR_AUTHENTICATION_FAILED` so something might be wrong with the keys.

The problem may be that they keys you are using are mixed up (private and public should switch place) or that they are not configured correctly on the host server. Or something like a missed character in copy-paste.

**Comment by daicaga** [comment]
Could I use the key with new line character in NSString via `\` like above?

**Comment by Lejdborg** [comment]
You should be able to to that, but you cannot indent the following lines. That will add spaces/tabs to the key.

**Comment by daicaga** [comment]
I really don't know why, but when I use 2 files for public and private keys. It runs well, But use function in memory, it cannot authentication with server.

Regards,
Ga

**Comment by Lejdborg** [comment]
If you use code like the one you posted above it wont work. You are messing up the key data with whitespace that shouldn't be there. Try it without newlines and it probably works.

**Comment by rrath-compumatrice** [comment]
@daicaga  Were you able to resolve the issue and how did u fix it? Can you please post some code snippet?

-Thank you

**Comment by Pan-Wu** [comment]
@rrath-edr You can try to check the log on your server here: /var/log/secure.
