### ISSUE TITLE
Add information to export compliance to readme or new doc

### ISSUE THREAD

**Issue by ChristianVirtual** [NMSSH/NMSSH#172]
Start using you great work in one of my iOS apps and really benefit from it as it allows me to communicate with connected Linux systems very easy. 
Could you add some information, based on your experience, with respect to the need for export compliance ? What information we as developer have to submit to the BIS when using your lib.
Sure with a disclaimer that it would be not legal advise and the developer is responsible himself. But some share of experience (also from other user) would be much appreciated.

**Comment by ChristianVirtual** [comment]
Could you please also share the used source for libssh2 ? Or guide me to the referernece ?

**Comment by Frugghi** [comment]
To compile the library I use [this script](https://github.com/Frugghi/iSSH2), the source is downloaded from the official website. You can easly replace the library with a version compiled by you. It's safer to compile open source library on your own.
