### ISSUE TITLE
Rebuilding libssh

### ISSUE THREAD

**Issue by schwa** [NMSSH/NMSSH#174]
Are the "recipes" to build libssh for NMSSH Included in this project?

It's hard to 100% guarantee trust for a project that includes a binary only version of libssh in the project.

**Comment by Frugghi** [comment]
The libraries are compiled with [this script](https://github.com/Frugghi/iSSH2)

**Comment by schwa** [comment]
This doesn't seem to be in the README - adding it to README might be very useful for users.

**Comment by Frugghi** [comment]
Done :+1: 

Thank you!
