### ISSUE TITLE
 Execute a interactive shell command

### ISSUE THREAD

**Issue by TzYung** [NMSSH/NMSSH#186]
Hello,
Thanks for sharing this great project.
Currently, I am executing an interactive command on the connected server, this process will return some strings first after called,  then I need to use this response to generate a password  and send back the server to complete this process. 

But I couldn't get the first response after execute this command...
Is it possible for NMSSH to interact with a process running, instead of waiting for the process to exit to return the response?

 [session.channel setRequestPty:YES];
 [session.channel setPtyTerminalType:NMSSHChannelPtyTerminalAnsi];
  NSString *response = [session1.channel execute:@"interactive command" error:&error];

Kind regards,

**Comment by Lejdborg** [comment]
Use the `-[NMSSHChannel write:error:timeout]` method with the interactive terminal. Example application [here](https://github.com/NMSSH/NMSSH/tree/master/Examples/PTYExample).
