### ISSUE TITLE
Shell: strange characters when nodejs prompts user

### ISSUE THREAD

**Issue by oz-** [NMSSH/NMSSH#196]
Hello and thank you for sharing this great framework.

I'm currently building an application to connect to a RaspberryPi via SSH. 
My first work was to learn about your library by building a terminal-like view, like in your iOS example. 

Everything seems to work fine, except that I receive strange response from the server when launching _nodejs_ (without parameters). 

In the terminal, nodejs response looks like only a **>** character, but in my app (and in your example, the message sent by the channel is **[1G[0J> [3G**

Also, sending Control+C (0x03) doesn't work as expected when nodejs prompts the user: 

> 
> (^C again to quit)
> [1G[0J> [3G
> 
> [90mundefined[39m
> [1G[0J> [3G

Did you meet this kind of behavior before ? 

Thank you !

**Comment by Frugghi** [comment]
Are you using a pseudo-terminal? It seems like you're receiving [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code). I guess nodejs output has colors...

**Comment by oz-** [comment]
Yes, actually that was the issue. Thank you.
