### ISSUE TITLE
Build for Linux ?

### ISSUE THREAD

**Issue by smoegel** [NMSSH/NMSSH#199]
Do you have a plan to extend builds for Linux please?
Or does exist a way how to compile NMSSH under Linux and use it with swift for Linux ?
thnx

**Comment by Lejdborg** [comment]
NMSSH uses Apple APIs and will not work on Linux. You can look at the source implementation to build your own Swift wrapper for libssh2.

**Comment by smoegel** [comment]
I know it will no so easy but I will try :-)
thank you
