### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [NMSSH/NMSSH#200]
I have a problem with upload method. It allways return NO in my iOS app.

I debugged the code of NMSSH pod and the error is in NMSSHChannel.m file near line code 537.

`// Try to send a file via SCP.
    struct stat fileinfo;
    stat([localPath UTF8String], &fileinfo);
    LIBSSH2_CHANNEL *channel = libssh2_scp_send64(self.session.rawSession, [remotePath UTF8String], fileinfo.st_mode & 0644,
                                                  (unsigned long)fileinfo.st_size, 0, 0);;`

the variable channel is allways NULL. So the next code

            if (channel == NULL) {
                        NMSSHLogError(@"Unable to open SCP session");
                        fclose(local);
                        return NO;
            }

Exit from the upload method. 

The thing that I don't understand is why my error is "Unable to open SCP session". Before send a file, I have a session connected and authorized.

            NMSSHSession *session = [NMSSHSession connectToHost:hostFtp
                                                   withUsername:usernameFtp];
            
            if (session.isConnected) {
                [session authenticateByPassword:passwordFtp];
                
                if (session.isAuthorized) {
                    NSLog(@"sendFile - sftp Authentication succeeded");
                    [session.sftp connect];
                    if(session.isConnected) {
                        NSLog(@"sendFile - sftp Session connected");
                        BOOL success = [session.channel uploadFile:fileName to:directoryFtp];
                        if(success) {
                            NSLog(@"sendFile - sftp Transfer succeded");
                        }
                        else {
                            NSLog(@"sendFile - sftp Transfer failed");
                        }
                        [session disconnect];
                    }
                }
                else {
                    NSLog(@"sendFile - sftp not authorized");
                }
            }

And the 2 paramenters passed to the uploadFile are fine.
fileName is verified by checking if file really exists, and directoryFtp is something like DIR1/DIR2/DIR3/.

Can someone help me?

**Comment by Frugghi** [comment]
You're opening a SFTP session (`[session.sftp connect]`) and then you're using SCP (`[session.channel uploadFile:fileName to:directoryFtp]`).

SFTP and SCP are two different protocols. I guess that what you're looking for is:
```ObjC
/**
 Overwrite the contents of a file
 If no file exists, one is created.
 @param localPath File path to read bytes at
 @param path File path to write bytes at
 @returns Write success
 */
- (BOOL)writeFileAtPath:(NSString *)localPath toFileAtPath:(NSString *)path;
```
