### ISSUE TITLE
Trouble implementing

### ISSUE THREAD

**Issue by SpartanEngr1297** [NMSSH/NMSSH#204]
<img width="882" alt="screen shot 2017-02-08 at 2 29 56 pm" src="https://cloud.githubusercontent.com/assets/15006361/22753731/2aecd446-ee0b-11e6-82ea-c2218448c313.png">

This is my first time implementing NMSSH and I'm having a hard time. I've already created the bridging header so that I could run Obj-C through Swift but I still seem to be getting quite a few errors. Essentially I want to use NMSSH to connect to a server and then retrieve information off that server but as you can see I can't seem to get it established.

**Comment by Frugghi** [comment]
You are using Obective-C syntax inside a Swift file, you can't do that. You can use Objective-C classes from Swift but inside a `.swift` file you can only use Swift syntax.

**Comment by SpartanEngr1297** [comment]
Okay is there anyway to implement NMSSH into a swift file or does it have to be written into an objective-c file?

**Comment by Frugghi** [comment]
[This document from Apple documentation](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html) explains very well how to interact with Objective-C APIs from a Swift file.

You just need to convert the Objective-C code in your screenshot to Swift code. You can use any Objective-C class/framework from Swift.
