### ISSUE TITLE
Unable to open a session

### ISSUE THREAD

**Issue by SpartanEngr1297** [NMSSH/NMSSH#205]
I was able to get NMSSH up and running totally fine with one server but another server I try to connect to just says "Unable to open a session" when trying to authenticate. I used some print statements and it seems that it is able to connect to the server but then has issues when trying to authenticate. Any suggestions on what might be causing this error and how to possibly fix it?

**Comment by Lejdborg** [comment]
It might be that the authentication method you are trying to use is not supported by your server. Not all servers allow plain password authentication for example.

**Comment by SpartanEngr1297** [comment]
Okay is there a way to change the authentication method that NMSSH is using or is there any alternative authentication methods built in that I could change to?

**Comment by Frugghi** [comment]
You can get the list of supported authentication methods by your server calling [supportedAuthenticationMethods](https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSSHSession.h#L276-L281) of [NMSSHSession](https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSSHSession.h).

NMSSH supports authentication by password, public key or keyboard interactive. If your server doesn't requires authentication the [authorized](https://github.com/NMSSH/NMSSH/blob/master/NMSSH/NMSSHSession.h#L207-L211) property will be `true` after the connection has been established.

**Comment by SpartanEngr1297** [comment]
Okay thank you, I'll look into that. Also did find out that the server I could connect to was set up with OpenSSH 6.7 and the server I could not was set up with OpenSSH 5.3 do you think that might play a factor at all?

**Comment by Frugghi** [comment]
The server version shouldn't be relevant at all. The log of NMSSH might be useful to understand your issue.

**Comment by SpartanEngr1297** [comment]
It still wasn't working with the `authenticateByPassword` method so I created a public and private key with the server and tried to use `authenticateByPublicKey` method instead. Now in the log it's failing with: `NMSSH: Public key authentication failed with reason -16`

**Comment by Lejdborg** [comment]
What is the result of your call to `supportedAuthenticationMethods`?

You should create your private and public key on your own machine, and configure the server to accept your public key for authentication (can you login in using your terminal with the keys?)

**Comment by SpartanEngr1297** [comment]
Yes I can log in using my keys and when I call `supportedAuthenticationMethods` it returns:

```
Auth methods: (
    publickey,
    "keyboard-interactive",
    hostbased
)
```

**Comment by SpartanEngr1297** [comment]
Okay I figured it out, it did not work using the public/private keys but it did work by using this command:
```
[session authenticateByKeyboardInteractiveUsingBlock:^NSString *(NSString *request) {
        return <my password>;
    }];
```
