### ISSUE TITLE
Authenticate with a single key?

### ISSUE THREAD

**Issue by mikeCalvir** [NMSSH/NMSSH#210]
Hi,

I have the feeling I am overlooking something blatantly obvious and so I apologise in advance, this isn't really an Issue with the code but a question of user education.
But hopefully someone can help me out :)

I have been given  access to an SFTP server with a PEM file. 
I access the server from macOS as follows:

> sftp -i my.pem user@host

That works fine, and I am immediately connected, with no password/phrase required.

So I would now like my iOS app using NMSSH to be able to access this in the same way. 
I am trying to use authenticateByPublicKey:privateKey:andPassword:, but I always get back an error -16

NMSSH: User auth list: publickey
NMSSH: Public key authentication failed with reason -16

Any help greatly appreciated, thanks in advance!

Mike

**Comment by mikeCalvir** [comment]
Ok, it turns out I was just being an idiot, for about 2 hours at least.

**Comment by maxisme** [comment]
why? I think I must be too!
