### ISSUE TITLE
Xcode 8.3 Release build issue

### ISSUE THREAD

**Issue by mariuskurgonas** [NMSSH/NMSSH#216]
Hi,

I have updated to Xcode 8.3 and all was fine in Debug build, but when i did Release build - session would not connect returning -1 error code. Then i downgraded to Xcode 8.2.1, and Release build worked again. I suspect that some flags were changed and stuff like that (which i was not able to locate), so could you please update the project for Xcode 8.3 Release build compatibility?

Thanks

**Comment by miyang23** [comment]
fix:


    CFDataRef addressDataRef = NULL;

    while (addresses && ++index < [addresses count] && error) {
        NSData *addressData = addresses[index];
        NSString *ipAddress;

        // IPv4
        if ([addressData length] == sizeof(struct sockaddr_in)) {
            struct sockaddr_in address4;
            [addressData getBytes:&address4 length:sizeof(address4)];
            address4.sin_port = htons(port);

            address = (struct sockaddr_storage *)(&address4);
            address->ss_len = sizeof(address4);

            char str[INET_ADDRSTRLEN];
            inet_ntop(AF_INET, &(address4.sin_addr), str, INET_ADDRSTRLEN);
            ipAddress = [NSString stringWithCString:str encoding:NSUTF8StringEncoding];
            addressFamily = AF_INET;
            
            addressDataRef = CFDataCreate(kCFAllocatorDefault, (UInt8 *)&address4, address->ss_len);

        } // IPv6
        else if([addressData length] == sizeof(struct sockaddr_in6)) {
            struct sockaddr_in6 address6;
            [addressData getBytes:&address6 length:sizeof(address6)];
            address6.sin6_port = htons(port);

            address = (struct sockaddr_storage *)(&address6);
            address->ss_len = sizeof(address6);

            char str[INET6_ADDRSTRLEN];
            inet_ntop(AF_INET6, &(address6.sin6_addr), str, INET6_ADDRSTRLEN);
            ipAddress = [NSString stringWithCString:str encoding:NSUTF8StringEncoding];
            addressFamily = AF_INET6;
            
            addressDataRef = CFDataCreate(kCFAllocatorDefault, (UInt8 *)&address6, address->ss_len);
        }
        else {
            NMSSHLogVerbose(@"Unknown address, it's not IPv4 or IPv6!");
            continue;
        }
        
        // Try to create the socket
        _socket = CFSocketCreate(kCFAllocatorDefault, addressFamily, SOCK_STREAM, IPPROTO_IP, kCFSocketNoCallBack, NULL, NULL);
        if (!_socket) {
            NMSSHLogError(@"Error creating the socket");
            return NO;
        }
        
        // Set NOSIGPIPE
        int set = 1;
        if (setsockopt(CFSocketGetNative(_socket), SOL_SOCKET, SO_NOSIGPIPE, (void *)&set, sizeof(set)) != 0) {
            NMSSHLogError(@"Error setting socket option");
            [self disconnect];
            return NO;
        }

        error = CFSocketConnectToAddress(_socket, addressDataRef, [timeout doubleValue]);

**Comment by mariuskurgonas** [comment]
Thanks, will this be pushed to the master any time soon?

**Comment by Frugghi** [comment]
Thanks for the patch!
