### ISSUE TITLE
kCFSocketError (-1) for unknown reason

### ISSUE THREAD

**Issue by mikeCalvir** [NMSSH/NMSSH#219]
Scenario:
Two iPads, A B, both identical model and iOS version.
Both running the same app version, on the same WiFi network.

On A, everything works fine and we get connections. It never seems to go wrong.
On B, we get this error line output from this code in NMSSHSession.m:

`        error = CFSocketConnectToAddress(_socket, address, [timeout doubleValue]);
        CFRelease(address);

        if (error) {
            NMSSHLogVerbose(@"Socket connection to %@ on port %ld failed with reason %li, trying next address...", ipAddress, (long)port, error);
        }`
(Line 278)

And it happens every time. Device B fails consistently.
And I don't know what else to try at the moment (I don't have direct access to the iPads, this is at a distance with a client).

Any ideas from anyone are welcome! Thanks!

**Comment by Frugghi** [comment]
Are you using NMSSH 2.2.7? There is an issue with previous version when the app is compiled with Xcode 8.3

**Comment by mikeCalvir** [comment]
You're exactly right, I spotted it shortly after posting this, all is fine now :)
