### ISSUE TITLE
Could you please make release with Xcode 9 fix

### ISSUE THREAD

**Issue by larryonoff** [NMSSH/NMSSH#232]

**Comment by nitinchouhan123** [comment]
Hey can u check issue#233 ? is your issue same ?

**Comment by larryonoff** [comment]
Nope. I had an issue with compilation.

**Comment by larryonoff** [comment]
@nitinchouhan123 I don't know anything about this issue.

**Comment by Frugghi** [comment]
Hey, sorry for the delay. NMSSH 2.2.8 is now available on Cocoapods!

**Comment by larryonoff** [comment]
@Frugghi thanks!
