### ISSUE TITLE
Unable to build using Carthage with Xcode 9 installed

### ISSUE THREAD

**Issue by marceltex** [NMSSH/NMSSH#234]
I recently updated to Xcode 9. When I try building NMSSH using Carthage, the build fails and I get the following errors in the terminal's output:

`The following build commands failed:`

`CompileC /Users/marcel/Library/Developer/Xcode/DerivedData/Examples-bbjnjsjnkbdmkpefiwdkcsukypbr/Build/Intermediates.noindex/NMSSH-iOS.build/Release-iphoneos/NMSSH.build/Objects-normal/arm64/socket_helper.o NMSSH/Config/socket_helper.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/marcel/Carthage2/Carthage/Checkouts/NMSSH/NMSSH/Config/socket_helper.m:30:10: warning: implicit declaration of function 'select' is invalid in C99 [-Wimplicit-function-declaration]
/Users/marcel/Carthage2/Carthage/Checkouts/NMSSH/NMSSH/Config/socket_helper.m:30:10: error: implicit declaration of function 'select' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
/Users/marcel/Carthage2/Carthage/Checkouts/NMSSH/NMSSH/Config/socket_helper.m:30:10: error: declaration of 'select' must be imported from module 'Darwin.POSIX.sys.time' before it is required
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/marcel/Carthage2/Carthage/Checkouts/NMSSH/Examples/Examples.xcworkspace -scheme NMSSH -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **`

`The following build commands failed:`

`CompileC /Users/marcel/Library/Developer/Xcode/DerivedData/Examples-bbjnjsjnkbdmkpefiwdkcsukypbr/Build/Intermediates.noindex/NMSSH-iOS.build/Release-iphoneos/NMSSH.build/Objects-normal/arm64/socket_helper.o NMSSH/Config/socket_helper.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

Carthage build use to work fine on my machine while Xcode 8 was installed.

**Comment by nitinchouhan123** [comment]
Need Help-

Hey, I am assuming that you are using this library from quite some time.
I am new to this. Do you have any idea about the issue I am hitting on issue#233?

-Nitin

**Comment by PawelDecowski** [comment]
This issue isn’t limited to Carthage. It happens regardless of the dependency manager. Build fails in Xcode 9.

**Comment by PawelDecowski** [comment]
Seems this was fixed in https://github.com/NMSSH/NMSSH/commit/2746621381fa2822663cc8e3e2071034611d6be4. Not sure why I’m not getting the updated version using Cocoa Pods.

**Comment by PawelDecowski** [comment]
Ah, because I didn’t run `pod update`. 🤦‍♂️

**Comment by PawelDecowski** [comment]
Right, so the fix has been committed but hasn’t been released yet. Any reason why it hasn’t been tagged?

**Comment by nitinchouhan123** [comment]
Hi Pawel

Please can you look into the issue#233, in case you have any inputs please let me know.

-Nitin

**Comment by marceltex** [comment]
@PawelDecowski Thanks for pointing out that this has been fixed and committed. I guess I'll just have to wait for it to be released before I can build with Carthage again.

**Comment by marceltex** [comment]
Closed since this issue is actually identical to issue #232

**Comment by Frugghi** [comment]
NMSSH 2.2.8 is available on Cocoapods now, I was on holiday and I forgot to do the release!
