### ISSUE TITLE
Downloading large files through SFTP

### ISSUE THREAD

**Issue by o15a3d4l11s2** [NMSSH/NMSSH#246]
Is there a way to download large files through SFTP using relative paths or other method that does not store the whole file data in the memory?

Since I am downloading the files through SFTP I use
`- (NSData *)contentsAtPath:(NSString *)path progress:(BOOL (^)(NSUInteger got, NSUInteger totalBytes))progress` from `NMSFTP`

The issue is that the files are around 450 MB and therefore a lot of memory is used to store the data while reading the file.

I have checked
`- (BOOL)downloadFile:(NSString *)remotePath to:(NSString *)localPath progress:(BOOL (^)(NSUInteger, NSUInteger))progress` from `NMSSHChannel`,
but it hangs on
`LIBSSH2_CHANNEL *channel = libssh2_scp_recv(self.session.rawSession, [remotePath UTF8String], &fileinfo);` and never proceeds.

**Comment by o15a3d4l11s2** [comment]
@Frugghi, do you have any suggestions?

**Comment by Frugghi** [comment]
I've added a new version of `contentsAtPath:` that writes the data to a stream, you can use it to download the file directly to disk!
