### ISSUE TITLE
Build and Run on my Iphone X - arm64 error

### ISSUE THREAD

**Issue by MarioPAlmeidaZH** [NMSSH/NMSSH#253]
Dear Community,

I'm pretty new on GITHub and in IOS / Objective C programming. My experience is more about C#, .net and c++, so forgive me if my question is trivial for you.

I did a simple application to send commands via SSH to control a specific HW from Barix, and after a few hours was all perfect. Documentation of NMSSH lib was pretty clean and straightforward. congrats for that, rarely we can find such good work.

My problem is when I compile. if I use simulator of iPhone, all perfect, but when I load on my device to test there, an error occur as picture below:
<img width="1385" alt="screen shot 2018-07-27 at 23 10 07" src="https://user-images.githubusercontent.com/41806320/43346948-a32a366e-91f3-11e8-95ac-0bb153aab5b7.png">

I did all steps as recommended and using iPhone X simulated works perfect, only when I try my device this happens.

I tried to compile as new (after clean first), my app and also the lib NMSSH, choosing my device as target, and setting config in "build settings / "valid architectures", choosing arm64, arm7 and arm7s.

what can be wrong with my code? 

the target file that seems wrong on architecture "ViewControler.o", I cannot even find it on my disk. not even in finder.... seems to be bundled somewhere..

some screens:
<img width="1386" alt="screen shot 2018-07-27 at 23 24 51" src="https://user-images.githubusercontent.com/41806320/43347113-537a5cc4-91f4-11e8-8dc9-b40563a04fbd.png">
<img width="1387" alt="screen shot 2018-07-27 at 23 25 02" src="https://user-images.githubusercontent.com/41806320/43347118-5754e7d8-91f4-11e8-8afb-78e55ef31b05.png">

I also see that after compile the MNSSH, I copy the framwork to my code, as referred on user guide, but then if I look to content, is no more than header files..shouldn't be also "bin" files together? 

Thank you in advanced!

**Comment by ColdGrub1384** [comment]
In Xcode, a framework will not compile for all architectures, if you change valid architectures, it means it can compile for those architectures but not for all at the same time.

So, try including the library with Cocoapods, so the framework will compile with your app.

You can also try this:

- Compile the framework for real device and for simulator
- Show both products in the Finder
- Copy one of those frameworks
- Remove the binary: `NMSSH Copy.framework/Versions/Current/NMSSH`
- And in the terminal, type: `lipo <The framework for real device>/Versions/Current/NMSSH <The framework for simulator/Versions/Current/NMSSH> -output NMSSH Copy.framework/Versions/Current/NMSSH`
This will generate an universal framework.

**Comment by MarioPAlmeidaZH** [comment]
Dear ColdGrub1384 ,

thank you very much for your feedback..

I tried to find online some info how to "include library with Cocoapods without success. could you kindly guide me? I searched and tried many options of Xcode ..also nothing worked...
I did try your second tip, by "lipo" command does not work..for some reason seems to miss something.. I also verified that locations "/Versions/Current/NMSSH" and "Copy.framework/Versions/Current/NMSSH" does not exist on my disk... but could find something like "/Users/marioalmeida/Library/Developer/Xcode/DerivedData/NMSSH-iOS-gymggzguwdkltpggluzmhpchukhf/Build/Intermediates.noindex/NMSSH-iOS.build/Debug-iphoneos/NMSSH.build/Objects-normal/arm64" in my hard disk...so means xcode is compiling to arm64 in opposite of the error mentioned... any idea?

**Comment by ColdGrub1384** [comment]
To install a library with Cocoapods, you need to install Cocoapods by running `sudo gem install cocoapods`. After that, `cd <Your project's directory>` and `pod init`. A file named `Podfile` will be created. Edit it, it should look like:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '<Your target>' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for <Your target>  
end
```

Add below `# Pods for <Your target>  ` `pod 'NMSSH'`, so the file should look like:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '<Your target>' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for <Your target>  

  pod 'NMSSH'
end
```

Run `pod install` and open the generated `xcworkspace` file instead of the `xcodeproj`.

I saw that `<Framework>/Versions/Current/NMSSH` doesn't exist, so it's `<Framework>/NMSSH`

For the lipo method, build the framework for the simulator, go to the `Products` group, right click on `NMSSH.framework` to locate the framework and do the same thing for iOS. So you have the framework for simulator and for iOS.


I built the universal framework for you:
[NMSSH universal.framework.zip](https://github.com/NMSSH/NMSSH/files/2238379/NMSSH.universal.framework.zip)

I made a video for the lipo method because it's hard to explain:
https://vimeo.com/user74753342/review/282143828/accf8958fb

**Comment by MarioPAlmeidaZH** [comment]
Thank you very much for your help and patience . I performed the steps above, creating the xcworkspace. now all good and works! perfect!
