### ISSUE TITLE
publicKey should be nullable

### ISSUE THREAD

**Issue by mehmetfarhan** [NMSSH/NMSSH#255]
When i try to authenticate the session by private key, 
and sent the public key as _empty string_ i got error .

**publicKey should sent as nil to fix this issue.**

**Before:**
- (BOOL)authenticateByPublicKey:(nullable NSString *)publicKey
                     privateKey:(nonnull NSString *)privateKey
                    andPassword:(nullable NSString *)password;

**After:**
- (BOOL)authenticateByPublicKey:(nonnull NSString *)publicKey
                     privateKey:(nonnull NSString *)privateKey
                    andPassword:(nullable NSString *)password;

**Comment by Frugghi** [comment]
Thanks!

**Comment by JohnWickham** [comment]
I know this was closed a while ago, but hoping someone will know what’s up with this:

Version 2.3.1 installed using Cocoapods doesn't include the changes in 94624c9; public key is still `nonnull`. Does anyone know why Cocoapods doesn't have these changes?
